LINUX_PATH = -I$(TOPDIR)/src/kern-ucore/kmodule/linuxAdapter/include/
LINUX_PATH += -I$(TOPDIR)/src/kern-ucore/kmodule/linuxAdapter/include/uapi
TARGET_CFLAGS += $(LINUX_PATH)
obj-y := mod.o
dirs-y := modules
